config/routes.rb
Rails.application.routes.draw do
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root to: "homes#top"
  get "home/about" => "homes#about"
  resources :users
  resources :books do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end  
  get '/search', to: 'searches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy 
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
  
  
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end


  
  def after_sign_out_path_for(resource)
    root_path
  end
  
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = book.id
    @comment.save
  end
  
  def destroy
    @comment = BookComment.find_by(book_id: params[:book_id], id: params[:id])
    @comment.destroy
  end  
  
  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @user = current_user
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end  
  end
  
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book),notice: "You have created book successfully."
    else
      @user = current_user
      @books = Book.all
      render :index
    end  
  end  
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book),notice: "You have updated book successfully."
    else
      render :edit
    end  
  end  
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end  
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
  end
  
  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

	def search
	  @model = params[:model]
	  @content = params[:content]
	  @method = params[:method]
	  if @model == 'user'
	    @records = User.search_for(@content, @method)
	  else
		  @records = Book.search_for(@content, @method)
	  end
	end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    @books = @user.books
  end

  def index
    @user = current_user
    @users = User.all
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end  
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user),notice: "You have updated user successfully."
    else
      render :edit
    end  
  end  
  
  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_counter.html.erb
コメント数: <%= book.book_comments.count %>

app/views/book_comments/_form.html.erb
<%= form_with(model:[book, book_comment], local: false) do |f| %>
  <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class: "w-100" %>
  <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <tbody>
    <% book.book_comments.each do |book_comment| %>
     <tr>
        <td>
          <%= link_to user_path(book_comment.user) do %>
            <%= image_tag book_comment.user.get_profile_image(100, 100) %><br>
            <%= book_comment.user.name %>
          <% end %>
        </td>
        <td><%= book_comment.comment %></td>
        <td>
          <% if book_comment.user == current_user %>
            <%= link_to "Destroy", book_book_comment_path(book, book_comment), method: :delete, class: "btn btn-danger pull-right",remote: true %>
          <% end %>
        </td>
     </tr>
    <% end %>
  </tbody>
</table>

app/views/book_comments/create.js.erb
$(".comment-textarea").val("")
$(".book_comments_<%= @comment.book.id %>").html("<%= j(render "book_comments/index", book: @comment.book) %>")
$(".counter_<%= @comment.book.id %>").html("<%= j(render "book_comments/counter", book: @comment.book)%>")

app/views/book_comments/destroy.js.erb
$(".book_comments_<%= @comment.book.id %>").html("<%= j(render "book_comments/index", book: @comment.book) %>")
$(".counter_<%= @comment.book.id %>").html("<%= j(render "book_comments/counter", book: @comment.book) %>")

app/views/books/_form.html.erb
<%= form_with(model: book) do |f| %>
  <div class="form-group">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %><br />
    <%= f.text_area :body %>
  </div>
  <div class="form-group">
    <%= f.submit "Create Book" %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to image_tag(book.user.get_profile_image(80, 80)),user_path(book.user) %></td>
        <td><%= link_to book.title,book_path(book) %></td>
        <td><%= book.body %></td>
        <td id="favorite_btn_<%= book.id %>"><%= render "favorites/btn", book: book %></td>
        <td>コメント数: <%= book.book_comments.count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <%= render "layouts/error", model: @book %>
      <%= form_with(model: @book) do |f| %>
        <div class="form-group">
          <%= f.label :title %><br />
          <%= f.text_field :title %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %><br />
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit "Update Book" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %> | <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<def class="d-flex justify-content-center mb-2">
  <%= render "searches/form" %>
</def>
<div class="container px-5 px-sm-0">
  <%= render "layouts/error", model: @book %>
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "index", books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@book.user) do %>
                <%= image_tag @book.user.get_profile_image(80, 80) %><br>
                <%= @book.user.name %>
              <% end %>
            </td>
            <td><%= link_to @book.title,book_path(@book) %></td>
            <td><%= @book.body %></td>
            <td id="favorite_btn_<%= @book.id %>"><%= render "favorites/btn", book: @book %></td>
            <td class="counter_<%= @book.id %>"><%= render "book_comments/counter", book: @book %></td>
            <% if @user.id == current_user.id %>
              <td><%= link_to "Edit", edit_book_path(@book),class: "btn btn-sm btn-success edit_book_17219" %></td>
              <td><%= link_to "Destroy", book_path(@book),method: :delete, class: "btn btn-sm btn-danger destroy_book_17219", data: {confirm: "削除しますか？"} %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class="book_comments_<%= @book.id %>">
        <%= render "book_comments/index", book: @book %>
      </div>
      <%= render "book_comments/form", book_comment: @book_comment, book: @book %>
    </div>
  </div>
</div>

app/views/favorites/_btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
    <%= book.favorites.count %>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$("#favorite_btn_<%= @book.id %>").html("<%= j(render "favorites/btn", book: @book) %>")

app/views/favorites/destroy.js.erb
$("#favorite_btn_<%= @book.id %>").html("<%= j(render "favorites/btn", book: @book) %>")

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_error.html.erb
<% if model.errors.any? %>
  <%= model.errors.count %> errors prohibited this obj from being saved:
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container mt-5">
    <div class="row">
    	<div class="mx-auto">
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <%= link_to root_path, class: "navbar-brand" do %>
        <span>Bookers</span>
      <% end %>
      <% if user_signed_in? %>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li>
              <%= link_to user_path(current_user), class: "nav-link text-light" do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: "nav-link text-light" do %>
                <i class="fas fa-users"></i> Users
              <% end %>
            </li>
            <li>
              <%= link_to books_path, class: "nav-link text-light" do %>
                <i class="fas fa-book-open"></i> Books
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path,method: :delete, class: "nav-link text-light" do %>
                <i class="fas fa-sign-out-alt"></i> Log out
              <% end %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav ml-auto">
            <li>
              <%= link_to root_path, class: "nav-link text-light" do %>
                <i class="fas fa-home"></i> Home
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path, class: "nav-link text-light" do %>
                <i class="fas fa-link"></i> About
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: "nav-link text-light" do %>
                <i class="fas fa-user-plus"></i> Sign up
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: "nav-link text-light" do %>
                <i class="fas fa-sign-in-alt"></i> Log in
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header" %>
      <main>
        <%= flash[:notice] %>
        <%= yield %>
      </main>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
  <%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.select :model, options_for_select({ "User" => "user", "Book" => "book" }) %>
    <%= f.select :method, options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
    <%= f.submit '検索' %>
  <% end %>
<% end %>

app/views/searches/search.html.erb
<% if @model == 'user' %>
  <h3>Users search for "<%= @content %>"</h3>
  <%= render 'users/index', users: @records %>
<% elsif @model == 'book' %>
  <h3>Books search for "<%= @content %>"</h3>
  <%= render 'books/index', books: @records %>
<% end %>

app/views/users/_index.html.erb
<table class="table table-hover table-inverse">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag(user.get_profile_image(80, 80)) %></td>
        <td><%= user.name %></td>
        <td><%= link_to "Show",user_path(user) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<%= image_tag(user.get_profile_image(100, 100)) %>
<table class="table">
  <tbody>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<%= link_to edit_user_path(user.id),class: "btn btn-outline-secondary btn-block edit_user_23058" do %>
  <i class="fas fa-user-cog"></i>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <%= render "layouts/error", model: @user %>
      <%= form_with(model: @user, method: :patch) do |f| %>
        <div class="form-group">
          <%= f.label :name %><br />
          <%= f.text_field :name %>
        </div>
        <div class="form-group">
          <%= f.label :image %><br />
          <%= f.file_field :profile_image %>
        </div>
        <div class="form-group">
          <%= f.label :introduction %><br />
          <%= f.text_area :introduction %>
        </div>
        <div class="form-group">
          <%= f.submit "Update User", class: "btn btn-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<def class="d-flex justify-content-center mb-2">
  <%= render "searches/form" %>
</def>
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "info", user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "index", users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "info", user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: Book.new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <%= render "books/index", books: @books %>
    </div>
  </div>
</div>